# Generated by Django 5.2.6 on 2026-01-03 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_san_pham', models.CharField(editable=False, max_length=150)),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('muc_canh_bao', models.IntegerField(default=5)),
                ('san_pham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='khohang', to='products.sanpham')),
            ],
        ),
    ]
