# Generated by Django 5.2.6 on 2026-01-11 13:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_sao', models.PositiveSmallIntegerField()),
                ('noi_dung', models.TextField()),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('da_duyet', models.BooleanField(default=True)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.sanpham')),
            ],
            options={
                'verbose_name': 'Đánh giá',
                'verbose_name_plural': 'Đánh giá',
                'ordering': ['-ngay_tao'],
                'unique_together': {('san_pham', 'khach_hang')},
            },
        ),
    ]
