# Generated by Django 5.2.6 on 2026-01-03 16:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dat', models.DateTimeField(default=django.utils.timezone.now)),
                ('tong_tien', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trang_thai', models.CharField(choices=[('CHO', 'Chờ xử lý'), ('DANG', 'Đang giao'), ('DA', 'Đã giao'), ('HUY', 'Đã hủy')], default='CHO', max_length=10)),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Đơn hàng',
                'verbose_name_plural': 'Đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='ChiTietDonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('san_pham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.sanpham')),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiets', to='orders.donhang')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn hàng',
                'verbose_name_plural': 'Chi tiết đơn hàng',
            },
        ),
        migrations.CreateModel(
            name='LichSuGiaoDich',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trang_thai_cu', models.CharField(blank=True, max_length=10, null=True)),
                ('trang_thai_moi', models.CharField(max_length=10)),
                ('thoi_gian', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_thay_doi', models.CharField(blank=True, max_length=100, null=True)),
                ('don_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_sus', to='orders.donhang')),
            ],
            options={
                'verbose_name': 'Lịch sử giao dịch',
                'verbose_name_plural': 'Lịch sử giao dịch',
            },
        ),
    ]
