# Generated by Django 5.2.6 on 2026-01-03 16:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_san_pham', models.CharField(max_length=20, unique=True)),
                ('ten_san_pham', models.CharField(max_length=150)),
                ('gia', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('so_luot_ban', models.IntegerField(default=0)),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='sanpham/')),
                ('so_luong_ton', models.IntegerField(default=0)),
                ('ngay_tao', models.DateTimeField(default=django.utils.timezone.now)),
                ('danh_muc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.danhmuc')),
            ],
        ),
    ]
